Fixed assets directory permissions

diff --git a/zabbix-appliance/ubuntu/Dockerfile.orig b/zabbix-appliance/ubuntu/Dockerfile.orig
--- a/zabbix-appliance/ubuntu/Dockerfile.orig
+++ b/zabbix-appliance/ubuntu/Dockerfile.orig
@@ -1,35 +1,42 @@
-FROM centos:centos7 as builder
+FROM ubuntu:bionic as builder
 
-ARG YUM_FLAGS_COMMON="-y"
-ARG YUM_FLAGS_DEV="${YUM_FLAGS_COMMON}"
+ARG APT_FLAGS_COMMON="-y"
+ARG APT_FLAGS_DEV="${APT_FLAGS_COMMON} --no-install-recommends"
 
 ARG MAJOR_VERSION=4.2
 ARG ZBX_VERSION=${MAJOR_VERSION}.1
 ARG ZBX_SOURCES=https://git.zabbix.com/scm/zbx/zabbix.git
 ENV ZBX_VERSION=${ZBX_VERSION} ZBX_SOURCES=${ZBX_SOURCES} \
+    LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8 TERM=xterm \
+    MIBDIRS=/var/lib/snmp/mibs/ietf:/var/lib/snmp/mibs/iana:/usr/share/snmp/mibs:/var/lib/zabbix/mibs MIBS=+ALL \
     ZBX_TYPE=server ZBX_DB_TYPE=mysql ZBX_OPT_TYPE=nginx \
     MYSQL_ALLOW_EMPTY_PASSWORD=true ZBX_ADD_SERVER=true ZBX_ADD_WEB=true DB_SERVER_HOST=localhost MYSQL_USER=zabbix ZBX_ADD_JAVA_GATEWAY=true ZBX_JAVAGATEWAY_ENABLE=true ZBX_JAVAGATEWAY=localhost
 
-RUN yum ${YUM_FLAGS_DEV} install http://repo.zabbix.com/non-supported/rhel/7/x86_64/iksemel-devel-1.4-2.el7.centos.x86_64.rpm \
-                                 http://repo.zabbix.com/non-supported/rhel/7/x86_64/iksemel-1.4-2.el7.centos.x86_64.rpm && \
-    yum --quiet makecache && \
-    yum ${YUM_FLAGS_DEV} install \
+RUN apt-get ${APT_FLAGS_COMMON} update && \
+    DEBIAN_FRONTEND=noninteractive apt-get ${APT_FLAGS_DEV} install locales && \
+    locale-gen $LC_ALL && \
+    apt-get ${APT_FLAGS_COMMON} update && \
+    DEBIAN_FRONTEND=noninteractive apt-get ${APT_FLAGS_DEV} install \
             autoconf \
             automake \
             gcc \
             gettext \
-            java-1.8.0-openjdk-devel \
-            libcurl-devel \
-            libevent-devel \
-            libssh2-devel \
-            libxml2-devel \
+            libc6-dev \
+            libcurl4-openssl-dev \
+            libevent-dev \
+            libiksemel-dev \
+            libldap2-dev \
+            libmysqlclient-dev \
+            libopenipmi-dev \
+            libpcre3-dev \
+            libsnmp-dev \
+            libssh2-1-dev \
+            libxml2-dev \
             make \
-            mariadb-devel \
-            net-snmp-devel \
-            OpenIPMI-devel \
-            openldap-devel \
+            openjdk-8-jdk \
+            pkg-config \
             git \
-            unixODBC-devel && \
+            unixodbc-dev && \
     cd /tmp/ && \
     git clone ${ZBX_SOURCES} --branch ${ZBX_VERSION} --depth 1 --single-branch zabbix-${ZBX_VERSION} && \
     cd /tmp/zabbix-${ZBX_VERSION} && \
@@ -71,25 +78,25 @@ RUN yum ${YUM_FLAGS_DEV} install http://repo.zabbix.com/non-supported/rhel/7/x86
     rm -rf tests && \
     ./locale/make_mo.sh
 
-FROM centos:centos7
+FROM ubuntu:bionic
 LABEL maintainer="Alexey Pustovalov <alexey.pustovalov@zabbix.com>"
 
 ARG BUILD_DATE
 ARG VCS_REF
 
-ARG YUM_FLAGS_COMMON="-y"
-ARG YUM_FLAGS_PERSISTENT="${YUM_FLAGS_COMMON}"
-
+ARG APT_FLAGS_COMMON="-y"
+ARG APT_FLAGS_PERSISTENT="${APT_FLAGS_COMMON} --no-install-recommends"
 ARG MAJOR_VERSION=4.2
 ARG ZBX_VERSION=${MAJOR_VERSION}.1
 ARG ZBX_SOURCES=https://git.zabbix.com/scm/zbx/zabbix.git
 ENV ZBX_VERSION=${ZBX_VERSION} ZBX_SOURCES=${ZBX_SOURCES} \
-    TERM=xterm MIBDIRS=/usr/share/snmp/mibs:/var/lib/zabbix/mibs MIBS=+ALL \
+    LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8TERM=xterm \
+    MIBDIRS=/var/lib/snmp/mibs/ietf:/var/lib/snmp/mibs/iana:/usr/share/snmp/mibs:/var/lib/zabbix/mibs MIBS=+ALL \
     ZBX_TYPE=server ZBX_DB_TYPE=mysql ZBX_OPT_TYPE=nginx \
     MYSQL_ALLOW_EMPTY_PASSWORD=true ZBX_ADD_SERVER=true ZBX_ADD_WEB=true DB_SERVER_HOST=localhost MYSQL_USER=zabbix ZBX_ADD_JAVA_GATEWAY=true ZBX_JAVAGATEWAY_ENABLE=true ZBX_JAVAGATEWAY=localhost
 ENV TINI_VERSION v0.18.0
 
-LABEL org.label-schema.name="zabbix-${ZBX_TYPE}-${ZBX_DB_TYPE}-centos" \
+LABEL org.label-schema.name="zabbix-${ZBX_TYPE}-${ZBX_DB_TYPE}-ubuntu" \
       org.label-schema.vendor="Zabbix LLC" \
       org.label-schema.url="https://zabbix.com/" \
       org.label-schema.description="Zabbix appliance with MySQL database support and ${ZBX_OPT_TYPE} web-server" \
@@ -100,7 +107,7 @@ LABEL org.label-schema.name="zabbix-${ZBX_TYPE}-${ZBX_DB_TYPE}-centos" \
       org.label-schema.usage="https://www.zabbix.com/documentation/${MAJOR_VERSION}/manual/installation/containers" \
       org.label-schema.version="${ZBX_VERSION}" \
       org.label-schema.vcs-url="${ZBX_SOURCES}" \
-      org.label-schema.docker.cmd="docker run --name zabbix-appliance -p 80:80 -p 10051:10051 -d zabbix-appliance:centos-${ZBX_VERSION}"
+      org.label-schema.docker.cmd="docker run --name zabbix-appliance -p 80:80 -p 10051:10051 -d zabbix-appliance:ubuntu-${ZBX_VERSION}"
 
 STOPSIGNAL SIGTERM
 
@@ -109,17 +116,23 @@ COPY --from=builder /tmp/zabbix-${ZBX_VERSION}/src/zabbix_get/zabbix_get /usr/bi
 COPY --from=builder /tmp/zabbix-${ZBX_VERSION}/src/zabbix_sender/zabbix_sender /usr/bin/zabbix_sender
 COPY --from=builder /tmp/zabbix-${ZBX_VERSION}/conf/zabbix_${ZBX_TYPE}.conf /etc/zabbix/zabbix_${ZBX_TYPE}.conf
 COPY --from=builder /tmp/zabbix-${ZBX_VERSION}/database/${ZBX_DB_TYPE}/create.sql.gz /usr/share/doc/zabbix-${ZBX_TYPE}-${ZBX_DB_TYPE}/create.sql.gz
-      
+            
 COPY --from=builder /tmp/zabbix-${ZBX_VERSION}/src/zabbix_java/bin/ /usr/sbin/zabbix_java/bin/
 COPY --from=builder /tmp/zabbix-${ZBX_VERSION}/src/zabbix_java/lib/ /usr/sbin/zabbix_java/lib/
-      
+            
 COPY --from=builder /tmp/zabbix-${ZBX_VERSION}/frontends/php/ /usr/share/zabbix/
 ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /sbin/tini
 
-RUN groupadd --system zabbix && \
-    adduser -r --shell /sbin/nologin \
-            -g zabbix -G dialout \
-            -d /var/lib/zabbix/ \
+RUN apt-get ${APT_FLAGS_COMMON} update && \
+    DEBIAN_FRONTEND=noninteractive apt-get ${APT_FLAGS_PERSISTENT} install locales gnupg2 && \
+    locale-gen $LC_ALL && \
+    echo "#!/bin/sh\nexit 0" > /usr/sbin/policy-rc.d && \
+    addgroup --system --quiet zabbix && \
+    adduser --quiet \
+            --system --disabled-login \
+            --ingroup zabbix \
+            --home /var/lib/zabbix/ \
+            --no-create-home \
         zabbix && \
     mkdir -p /etc/zabbix && \
     mkdir -p /var/lib/zabbix && \
@@ -136,44 +149,65 @@ RUN groupadd --system zabbix && \
     mkdir -p /var/lib/zabbix/ssl/ssl_ca && \
     chown --quiet -R zabbix:root /var/lib/zabbix && \
     mkdir -p /usr/share/doc/zabbix-${ZBX_TYPE}-${ZBX_DB_TYPE}/ && \
-    yum ${YUM_FLAGS_COMMON} makecache && \
-    yum ${YUM_FLAGS_PERSISTENT} install http://repo.zabbix.com/non-supported/rhel/7/x86_64/iksemel-1.4-2.el7.centos.x86_64.rpm \
-                                        http://repo.zabbix.com/non-supported/rhel/7/x86_64/fping-3.10-1.el7.x86_64.rpm  && \
-    yum ${YUM_FLAGS_PERSISTENT} install epel-release && \
-    yum ${YUM_FLAGS_PERSISTENT} install \
-            iputils \
+    apt-get ${APT_FLAGS_COMMON} update && \
+    NGINX_GPGKEY=573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62; \
+    found=''; \
+    for server in \
+        ha.pool.sks-keyservers.net \
+        hkp://keyserver.ubuntu.com:80 \
+        hkp://p80.pool.sks-keyservers.net:80 \
+        pgp.mit.edu \
+    ; do \
+        echo "Fetching GPG key $NGINX_GPGKEY from $server"; \
+        apt-key adv --keyserver "$server" --keyserver-options timeout=10 --recv-keys "$NGINX_GPGKEY" && found=yes && break; \
+    done; \
+    test -z "$found" && echo >&2 "error: failed to fetch GPG key $NGINX_GPGKEY" && exit 1; \
+    DISTRIB_CODENAME=$(/bin/bash -c 'source /etc/lsb-release && echo $DISTRIB_CODENAME') && \
+    echo "deb http://nginx.org/packages/ubuntu/ $DISTRIB_CODENAME nginx" >> /etc/apt/sources.list.d/nginx.list && \
+    apt-get ${APT_FLAGS_COMMON} update && \
+    DEBIAN_FRONTEND=noninteractive apt-get ${APT_FLAGS_PERSISTENT} install \
+            iputils-ping \
             traceroute \
             curl \
-            OpenIPMI-libs \
-            java-1.8.0-openjdk-headless \
-            libcurl \
-            libevent \
+            fping \
+            libcurl4 \
+            libevent-2.1 \
+            libiksemel3 \
+            libmysqlclient20 \
+            libopenipmi0 \
+            libpcre3 \
+            libsnmp30 \
+            libssh2-1 \
+            libssl1.1 \
             libxml2 \
-            mariadb \
-            mariadb-server \
-            net-snmp-libs \
+            mysql-client \
+            mysql-server \
             nginx \
-            openldap \
-            openssl-libs \
-            pcre \
-            php-bcmath \
-            php-fpm \
-            php-gd \
-            php-ldap \
-            php-mbstring \
-            php-mysql \
-            php-xml \
+            openjdk-8-jre-headless \
+            php7.2-bcmath \
+            php7.2-fpm \
+            php7.2-gd \
+            php7.2-json \
+            php7.2-ldap \
+            php7.2-mbstring \
+            php7.2-mysql \
+            php7.2-xml \
+            snmp-mibs-downloader \
             supervisor \
-            unixODBC && \
-    rm -f /etc/php-fpm.d/www.conf && \
-    mkdir -p /var/lib/php/ && \
-    chown --quiet -R nginx:nginx /var/lib/php/ && \
+            ca-certificates \
+            unixodbc && \
+    mkdir -p /var/lib/locales/supported.d/ && \
+    rm -f /var/lib/locales/supported.d/local && \
     cat /usr/share/zabbix/include/locales.inc.php | grep display | grep true | awk '{$1=$1};1' | \
                 cut -d"'" -f 2 | sort | \
-                xargs -I '{}' bash -c 'echo "{}" && localedef -c -i {} -f UTF-8 {}.UTF-8 2>/dev/null' && \
-    chown --quiet -R nginx:nginx /usr/share/zabbix && \
-    yum ${YUM_FLAGS_PERSISTENT} clean all && \
-    rm -rf /var/cache/yum/ && \
+                xargs -I '{}' bash -c 'echo "{}.UTF-8 UTF-8" >> /var/lib/locales/supported.d/local' && \
+    dpkg-reconfigure locales && \
+    apt-get ${APT_FLAGS_COMMON} autoremove && \
+    apt-get ${APT_FLAGS_COMMON} clean && \
+    mkdir -p /var/lib/php7 && \
+    chown --quiet -R www-data:www-data /var/lib/php7 && \
+    rm -rf /var/cache/nginx/* && \
+    rm -rf /var/lib/apt/lists/* && \
     chmod +x /sbin/tini
 
 EXPOSE 80/TCP 443/TCP 10051/TCP
@@ -190,8 +224,7 @@ COPY ["conf/etc/zabbix/nginx.conf", "/etc/zabbix/"]
 COPY ["conf/etc/zabbix/nginx_ssl.conf", "/etc/zabbix/"]
 COPY ["conf/etc/zabbix/web/zabbix.conf.php", "/etc/zabbix/web/"]
 COPY ["conf/etc/nginx/nginx.conf", "/etc/nginx/"]
-COPY ["conf/etc/php-fpm.conf", "/etc/php-fpm.conf"]
-COPY ["conf/etc/php.d/99-zabbix.ini", "/etc/php.d/99-zabbix.ini"]
+COPY ["conf/etc/php/7.2/fpm/conf.d/99-zabbix.ini", "/etc/php/7.2/fpm/conf.d/"]
 COPY ["conf/etc/zabbix/zabbix_java_gateway_logback.xml", "/etc/zabbix/"]
 COPY ["conf/usr/sbin/zabbix_java_gateway", "/usr/sbin/"]
 COPY ["docker-entrypoint.sh", "/usr/bin/"]
